name: Deploy Blazor WASM to GitHub Page
env:
  PUBLISH_DIR: bin/Release/net7.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.400'        

    - name: Publish application
      run: dotnet publish -c Release
        
    # base href url value should be changed so that resources like CSS and scripts can load properly. 
    - name: Rewrite base href
      if: success()
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: /home/runner/work/MyPortafolio/MyPortafolio/Portafolio/bin/Release/net7.0/publish/wwwroot/index.html
        base_href: MyPortafolio
        
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch /home/runner/work/MyPortafolio/MyPortafolio/Portafolio/bin/Release/net7.0/publish/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@4.4.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: /home/runner/work/MyPortafolio/MyPortafolio/Portafolio/bin/Release/net7.0/publish/wwwroot/ # The folder the action should deploy.
